[cosmic-ray]
module-path = "controllers"
timeout = 30.0
test-command = "python -m pytest tests"
excluded-modules = []

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.filters.operators-filter]
exclude-operators = []

