version: '1'
services:

    db:
        image: postgres
        environment:
            POSTGRES_DB: Student
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admpass
        ports:
            - "5432:5432"
    app:
        build: .
        ports:
            - "8003:8000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://admin:admpass@127.0.0.1:5432/Student
